[package]
name = "verinox"
version = "0.1.0"
edition = "2024"

[dependencies]
bytesize = { version = "2.7.0", features = ["serde"]}
const-hex = "1.19.1"
gethostname = "1.1.0"
glob = "0.3.4"
notify = "8.2.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
tempfile = "3.27.0"
thiserror = "2.0.20"
time = { version = "0.3.55", features = ["serde", "serde-well-known", "formatting", "macros", "parsing"] }
toml = "1.1.4"
