# Hashing algorithm to use when hashing files.
hash_algorithm = "sha256"
# Log Directory
log_dir = "/var/log/verinox"
# Maximum size of a single log file before it breaks off into a new file.
max_log_size = "10MB"
# watch_patterns are the directories to monitor for file changes.
watch_patterns = [
    '/etc/passwd', 
    '/etc/shadow', 
    '/etc/sudoers', 
    '/etc/sudoers.d/**', 
    '/etc/hosts', 
    '/etc/ssh/sshd_config', 
    '/etc/crontab', 
    '/etc/cron.d/**', 
    '/etc/systemd/system/**', 
    '/etc/ld.so.preload'
    ]
# File used to track the last known hash of each watched file, so changes can be detected across restarts.
baseline_path = "/var/lib/verinox/baseline.json"