# Hashing algorithm to use when hashing files.
hash_algorithm = "sha256"
# Log directory
log_dir = 'C:\ProgramData\Verinox\logs'
# Maximum size of a single log file before it breaks off into a new file.
max_log_size = "10MB"
# watch_patterns are the directories to monitor for file changes.
watch_patterns = [
    'C:\Windows\System32\drivers\etc\hosts', 
    'C:\Windows\System32\Tasks\**', 
    'C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\**', 
    'C:\Users\*\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\**', 
    'C:\Windows\win.ini', 
    'C:\Windows\system.ini'
    ]
# File used to track the last known hash of each watched file, so changes can be detected across restarts.
baseline_path = 'C:\ProgramData\Verinox\baseline.json'